import Head from 'next/head';
import GlobalExchange from '../components/GlobalExchange';

export default function Home() {
  return (
    <div>
      <Head>
        <title>CAB SHARE | IITH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center justify-center py-[5rem]">
        <GlobalExchange />
      </main>
    </div>
  );
}
